version: '3.9'

services:
  # Service Client
  client_service:
    build:
      context: ./Client
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db_client
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: restaurant_client
      PORT: 3000
      JWT_SECRET: your_jwt_secret
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
      db_client:
        condition: service_healthy

  # Service Commande
  commande_service:
    build:
      context: ./Commande
    ports:
      - "3001:3001"
    environment:
      JWT_SECRET: your_jwt_secret
      DATABASE_URL: mongodb+srv://lux:luxluxlux@cluster0.8sx89.mongodb.net/restaurant_commande
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy

  # Service Livraison
  livraison_service:
    build:
      context: ./Livraison-Api
    ports:
      - "4001:4001"
    environment:
      JWT_SECRET: your_jwt_secret
      DATABASE_URL: mongodb+srv://lux:luxluxlux@cluster0.8sx89.mongodb.net/restaurant_livraison
      RABBITMQ_URL: amqp://rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672" # Interface de gestion
      - "5672:5672"   # Port AMQP pour les connexions
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5

  # Base de données pour le service Client (MySQL)
  db_client:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: restaurant_client
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - client_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-padmin"]
      interval: 10s
      retries: 5

volumes:
  client_db_data:
